name: GitHub-PR
run-name: ${{ github.triggering_actor }} has opened a pull request
on: 
  pull_request:
    types: [opened,reopened,closed,converted_to_draft]
jobs:
  notify-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
