name: pull-request-opened
run-name: ${{ github.actor }} has opened a pull request
on: 
  pull_request:
    types: [opened]
jobs:
  notify-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
